"""RQ5 / T5.3-T5.6 — the clean bottleneck-rank sweep.

Removes the confound in the existing four budget points (linear_probe / LoRA /
bottleneck-parallel / full_ft), which vary budget TOGETHER WITH adapter type
and with which weights train. Here dataset (CIFAR-FS), backbone (ResNet-18),
shot count and adapter family (parallel 1x1 bottleneck) are all held fixed and
ONLY `adapter.rank` moves.

This is also the experiment that settles RQ3's causal ambiguity (T3.4): it
varies budget with backbone AND architecture fixed, which the Step 10 grid
cannot do.
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

from src.utils import load_config
from scripts.train import _head_descriptor, _checkpoint_tag

#: ~7 budget points spanning 2.9k -> 124k trainable params on ResNet-18.
#: 16 is the grid's frozen value, so the sweep passes exactly through the
#: existing Step 10 point rather than running parallel to it.
RANKS = (1, 2, 4, 8, 16, 32, 64)
SWEEP_SEEDS = (42, 43, 44)

PARENTS = {
    "evidential": "exp_phase3_placement_parallel_evidential.yaml",
    "softmax": "exp_phase3_placement_parallel_softmax.yaml",
}

#: Keys this generator is ALLOWED to differ on across the sweep. Everything
#: else must be byte-identical (T5.6) or the sweep silently reintroduces the
#: very confound it exists to remove.
ALLOWED_DIFF_PATHS = {
    "seed",
    "adapter.rank",
    "output.run_tag",
    "output.results_dir",
    "wandb.group",
    "wandb.tags",
    "wandb.mode",
    "wandb.disabled",
}


def sweep_cell_id(head: str, rank: int, seed: int) -> str:
    return f"rq5_r18_parallel_{head}_rank{rank}_seed{seed}"


def build_sweep_configs(repo_root: Path, heads=("evidential",),
                        ranks=RANKS, seeds=SWEEP_SEEDS,
                        out_dir_name="rq5", results_dir="results/rq5") -> list[dict]:
    """Write one YAML per (head, rank, seed) and return the index.

    Each file is a 5-key override on the SAME Step 6 parent config the grid
    used, so the recipe (LR, KL schedule, evidence affine, block_ids, epochs,
    patience) is inherited, never retyped.
    """
    cfg_dir = repo_root / "configs" / out_dir_name
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cells = []
    for head in heads:
        parent = PARENTS[head]
        for rank in ranks:
            for seed in seeds:
                cell = sweep_cell_id(head, rank, seed)
                run_tag = f"rq5_r18_parallel_rank{rank}"
                doc = {
                    "extends": f"../{parent}",
                    "seed": int(seed),
                    "adapter": {"rank": int(rank)},
                    "output": {"run_tag": run_tag,
                               "results_dir": results_dir},
                    "wandb": {"group": f"rq5-rank-sweep-{head}",
                              "tags": ["rq5", "rank_sweep", head]},
                }
                path = cfg_dir / f"{cell}.yaml"
                with open(path, "w") as f:
                    f.write(
                        "# RQ5 rank sweep (T5.3) — generated by the new_rqs "
                        "notebook, do not hand-edit.\n"
                        f"# Only adapter.rank and seed vary across this sweep; "
                        f"see the T5.6 guard.\n")
                    yaml.safe_dump(doc, f, sort_keys=False)

                merged = load_config(path)
                results_suffix = f"{cell}"
                cells.append({
                    "cell": cell, "head": head, "rank": int(rank), "seed": int(seed),
                    "config": str(path.relative_to(repo_root)),
                    "run_tag": run_tag,
                    "results_suffix": results_suffix,
                    "checkpoint": (f"checkpoints/model_phase2_"
                                   f"{_checkpoint_tag(merged)}.pt"),
                    "results_json": (f"{results_dir}/{results_suffix}_"
                                     f"{merged.adapter.type}_"
                                     f"{_head_descriptor(merged)}_metrics.json"),
                })
    index_path = cfg_dir / "_index.json"
    with open(index_path, "w") as f:
        json.dump({"cells": cells}, f, indent=2, sort_keys=True)
    return cells


# =====================================================================
# T5.6 — the guard that keeps the sweep a controlled experiment
# =====================================================================
def _flatten(d, prefix=""):
    out = {}
    for k, v in d.items():
        path = f"{prefix}.{k}" if prefix else str(k)
        if isinstance(v, dict):
            out.update(_flatten(v, path))
        else:
            out[path] = v
    return out


def assert_only_rank_and_seed_differ(repo_root: Path, cells: list[dict]) -> dict:
    """T5.6 — assert the MERGED configs differ only in rank, seed and the
    derived output/wandb bookkeeping.

    Checks the merged result, not the YAML source: a stray difference inherited
    from a parent would be invisible in the 5-key override files.
    """
    merged = {}
    for c in cells:
        merged[c["cell"]] = _flatten(dict(load_config(repo_root / c["config"])))

    keys = set()
    for m in merged.values():
        keys |= set(m.keys())

    offenders = {}
    for key in sorted(keys):
        if key in ALLOWED_DIFF_PATHS:
            continue
        vals = {json.dumps(m.get(key, "<MISSING>"), sort_keys=True, default=str)
                for m in merged.values()}
        if len(vals) > 1:
            offenders[key] = sorted(vals)[:4]

    return {
        "n_configs": len(cells),
        "n_keys_checked": len(keys - ALLOWED_DIFF_PATHS),
        "ok": not offenders,
        "offending_keys": offenders,
    }


def expected_trainable_params(rank: int,
                              stage_channels=(64, 128, 256, 512),
                              n_affine: int = 2) -> int:
    """Closed-form check on the parallel 1x1 bottleneck budget.

    Per stage: down 1x1 conv (C->r, +r bias) and up 1x1 conv (r->C, +C bias).
    Cross-checked against the committed grid value n_params=31746 at rank 16
    (ResNet-18, evidential: 2 extra evidence-affine scalars).
    """
    total = sum(2 * c * rank + rank + c for c in stage_channels)
    return total + n_affine
